# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec21d0d947ac84804b88fe69683082a162ce9be8440bb0a2c9a7c6fbe8aff0579da2a4e0b4e7d9e939d91b9137a668a001d99a4e6ddb3a7453f95c7a40e7a793

test:
  secret_key_base: c3432c685260d80d21c8efe794387e56f0ec887928edf09d9d0f77627be1523b7a065740a0716d3f94d2d7c809253f73051dad4ccaecc15ed93c0cc1c75f537c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
